name: Script tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: "Script tests (Node ${{ matrix.node }}, ${{ matrix.os }})"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [16, 18]
        os: [windows-latest, ubuntu-latest]
    steps:
      - name: "Checking-out code"
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2
        with:
          submodules: false

      - name: "Checking changed files"
        id: filter
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.11.1
        if: github.event_name == 'pull_request'
        with:
          filters: |
            packages:
              - 'packages/**/*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Defining cache"
        uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ matrix.node }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: "Defining node version"
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # v2
        with:
          node-version: ${{ matrix.node == 18 && '18.15.0' || matrix.node }}

      - name: "Installing dependencies"
        working-directory: ./
        if: steps.filter.outputs.packages == 'true'
        run: npm install

      - name: Increase number of watchers
        if: steps.filter.outputs.packages == 'true' && startsWith(matrix.os, 'ubuntu')
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - name: "Testing PWT commands"
        working-directory: ./
        if: steps.filter.outputs.packages == 'true'
        run: npm run test:pwt:commands
